### ISSUE TITLE
Improvements to the Numba-dppy test suite

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/numba-dppy#130]
The current test suite needs several improvements:

- [x] Move from Python unittest to pytest to allow parameterization.
  - [x] Run pytest in conda recipe (#222 )
- [x] Organize tests logically. At the least, we should split them into `dppy_kernel_tests` and `njit_tests`.
- [x] Tests should run for realistic problem sizes.
- [x] We need to run the test cases for multiple `dpctl.device_context` (`opencl:gpu`, `opencl:cpu`, `level0:gpu`).
- [x] The test cases should be run for multiple data types. To start with maybe `float32, float64` are sufficient, but later we should test for integer types, complex types, and reduced precision types.
- [ ] ~~Add tests for numpy broadcast operations. (Are there existing Numba tests that we can repurpose?)~~

**Comment by diptorupd** [comment]
@PokhodenkoSA @1e-to 

I have updated the description of the ticket to capture several improvements that are needed for our test suite.

I had to partially start addressing these improvemnets in #179 as I need to run our test cases for both OpenCL and LevelZero. Look at the [modified test_numpy_trigonometric_functions.py](https://github.com/IntelPython/numba-dppy/blob/8e0b151777c6b09be6a246ae6b22443ef9977625/numba_dppy/tests/njit_tests/test_numpy_trigonometric_functions.py) for an example of what I am proposing to do. Since, I did not know anything about `pytest` before today afternoon I may not be doing things quite right, so feel free to suggest changes.

**Comment by diptorupd** [comment]
@PokhodenkoSA why was this ticket closed? The sub-tasks that are outlined above are not yet addressed. Do we plan to open another ticket for those tasks?

**Comment by PokhodenkoSA** [comment]
It was closed by PR. But PR completed a part of work.

**Comment by diptorupd** [comment]
All the sub-task are complete except the broadcast operation. Numba-dppy does not support broadcast operations yet. I am closing the ticket, we can open more topical issues for test suite improvement in the future.
